---
title: "RMarkdown Presentation Formats"
author: "Cheng Peng"
date: "West Chester University"
output:
  beamer_presentation: 
    slide_level: 3
    includes:
      in_header: "wcu-RMD-slide-template.txt"
    theme: Goettingen
    fonttheme: professionalfonts
    colortheme: beaver
    fig_width: 3
    fig_height: 3
    toc: yes
    incremental: no
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = FALSE)
```


## Getting up 01

- Turn off alarm
- Get out of bed


## Breakfast 02

- Eat eggs
- Drink coffee


## basic presentation

* **ioslides** (HTML), 
* **Slidy** (HTML), 
* **Beamer**(PDF, MikTex is needed), and 
* **Power Point**. 


## THIS IS A TesT

* Bullet 1
* Bullet 2
* Bullet 3


## This is a summary

* This is a summarized table

```{r cars, echo = FALSE, comment = NA}
kable(summary(cars))
```


## A plot

* This is a plot

```{r pressure, echo=FALSE, fig.align='center'}
par(oma=c(0,0,0,0))
plot(pressure)
```

