---
title: "Visual Project Title"
author: "Your Name"
date: "STA 553"
output:
  html_document: 
    toc: yes
    toc_float: yes
    number_sections: yes
editor_options:
  chunk_output_type: inline
---


<style type="text/css">

div#TOC li {
    list-style:none;
    background-image:none;
    background-repeat:none;
    background-position:0;
}
h1.title {
  font-size: 24px;
  color: DarkRed;
  text-align: center;
}
h4.author { /* Header 4 - and the author and data headers use this too  */
    font-size: 18px;
  font-family: "Times New Roman", Times, serif;
  color: DarkRed;
  text-align: center;
}
h4.date { /* Header 4 - and the author and data headers use this too  */
  font-size: 18px;
  font-family: "Times New Roman", Times, serif;
  color: DarkBlue;
  text-align: center;
}
h1 { /* Header 1 - and the author and data headers use this too  */
    font-size: 22px;
    font-family: "Times New Roman", Times, serif;
    color: darkred;
    text-align: center;
}
h2 { /* Header 2 - and the author and data headers use this too  */
    font-size: 18px;
    font-family: "Times New Roman", Times, serif;
    color: navy;
    text-align: left;
}

h3 { /* Header 3 - and the author and data headers use this too  */
    font-size: 15px;
    font-family: "Times New Roman", Times, serif;
    color: navy;
    text-align: left;
}

h4 { /* Header 4 - and the author and data headers use this too  */
    font-size: 18px;
    font-family: "Times New Roman", Times, serif;
    color: darkred;
    text-align: left;
}
</style>

```{r, include=FALSE}
if (!require("tidyverse")) {
        install.packages("tidyverse")
        library(tidyverse)
}
if (!require("knitr")) {
        install.packages("knitr")
        library(knitr)
}
if (!require("plotly")) {
        install.packages("plotly")
        library(plotly)
}
if (!require("gapminder")) {
        install.packages("gapminder")
        library(gapminder)
}
if (!require("png")) {
        install.packages("png")              
        library("png")
}
if (!require("RCurl")) {
        install.packages("RCurl")         
        library("RCurl")
}
if (!require("colourpicker")) {
        install.packages("colourpicker")              
        library("colourpicker")
}
if (!require("gganimate")) {
        install.packages("gganimate")              
        library("gganimate")
}
if (!require("gifski")) {
        install.packages("gifski")              
        library("gifski")
}
if (!require("magick")) {
        install.packages("magick")              
        library("magick")
}
if (!require("grDevices")) {
        install.packages("grDevices")              
        library("grDevices")
}
if (!require("jpeg")) {
        install.packages("jpeg")              
        library("jpeg")
}
if (!require("rjson")) {
  install.packages("rjson")              
  library("rjson")
}
if (!require("RColorBrewer")) {
  install.packages("RColorBrewer")              
  library("RColorBrewer")
}
##
knitr::opts_chunk$set(echo = FALSE,       
                      warning = FALSE,   
                      result = TRUE,   
                      message = FALSE,
                      comment = NA)

```


\

# Introduction

Description of the data set .....

What types of visual exploratory analysis you plan to perform and motivation ......


# Meaningful Section Header for Visual Analysis 1

Outline the visual analysis briefly.....

 <table border = 0 bordercolor="darkgreen" bgcolor='#f6f6f6'  width=100%  align = center> 
        <tr>
            <td>
                You copy the code from Tableau and paste it here ......  
            </td>
       </tr>
 </table>      
            
Tell a brief story about the above Tableau graph .....            



# Meaningful Section Header for Visual Analysis 2            
            
Outline the visual analysis briefly.....

 <table border = 0 bordercolor="darkgreen" bgcolor='#f6f6f6'  width=100%  align = center> 
        <tr>
            <td>
                You copy the code from Tableau and paste it here ......  
            </td>
       </tr>
 </table>      
            
Tell a brief story about the above Tableau graph .....            
            
            
# Conclusion            
   
.......   